from: '"makeweb.io Support" <noreply@makeweb.io>'
subject: Password Reset from makeweb.io
content: |
  You receive this mail because there is a password reset request for the account using this email in makeweb.io. If you didn't ask for password reset, please just ignore this mail.

  To reset your password, click following link:

  [https://makeweb.io/me/passwd/reset/#{token}](https://makeweb.io/me/passwd/reset/#{token})

  Thanks,
  makeweb.io team
